services:
  postgres:
    image: postgres:16
    container_name: carstock_postgres
    environment:
      POSTGRES_USER: carstock_user
      POSTGRES_PASSWORD: carstock_pass
      POSTGRES_DB: carstock_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: carstock_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: