export enum NotificationType {
    LOW_STOCK = 'LOW_STOCK',
    NEW_BILL = 'NEW_BILL',
    DAILY_SUMMARY = 'DAILY_SUMMARY',
    WEEKLY_REPORT = 'WEEKLY_REPORT',
    SERVICE_REMINDER_DUE = 'SERVICE_REMINDER_DUE',
}
